import React from "react";
import axios from "axios";


import { Attr } from "./Attr";


export class Attraction extends React.Component {
	
constructor() {
	super();
	this.state = {
		items: []
	}
}

componentDidMount() {
	var data = [
	{
		"id": 23,
		"city_id": 3,
		"title_ru": "Цитадель Арк",
		"title_uz": "Ark",
		"title_en": "Ark",
		"waymark_ru": "",
		"waymark_uz": "",
		"waymark_en": "",
		"content_ru": "<p><i>Крепость Арк в Бухаре представляет собой восточный кремль. Хотя точных данных о его возрасте нет, в </i><i>VI</i><i> веке его стены уже надежно защищали местных правителей.</i></p><p><i></i></p>  <p>В начале XX века в цитадели проживало около трех тысяч человек. В основном это были приближенные эмира и знать. Еще здесь находились дворцовые службы, ремесленные мастерские и казначейство. Арк был средоточием всего, что представляло особую ценность для Бухарского Эмирата.</p>  <p>Он радушно принимал великих ученых и деятелей. Всемирно известный врач Авиценна зачитывался древними рукописями в уникальной библиотеке Арка. Также в нем жил поэт Омар Хайам, чьи мудрые рубаи переведены на многие языки.</p>  <p>История возникновения Арка окутана тайной. По легенде, красивый юноша Сиявуш влюбился в местную принцессу. Но правитель соглашался отдать за него свою дочь, если тот сможет построить дворец на земле, поместив его под бычьей шкурой. Смекалистый Сиявуш быстро нашел выход из положения. Он порезал шкуру, соединил концы тоненьких полосок и внутри условного кольца возвел прекрасный дворец.</p>  <p><strong>Конструкция и архитектура</strong></p>  <p>Величественное и неприступное фортификационное сооружение стояло на площади Регистан. Длина толстых стен высотой 16-20 м. составляла почти 800 м. На одной из них красовалась большая кожаная плеть (камча). Это был символ власти бухарского эмира.</p>  <p>Все сохранившиеся здания относятся к XVII - XX вв. Парадный въезд в крепость украшен двумя башнями. С помощью специальной галереи они соединяются с караульным помещением и террасами. Подъём к главным воротам представляет собой пандус. Через крытый длинный коридор он ведет к соборной мечети Джоме.</p>  <i>Крепость Арк является самым древним архитектурно-археологическим памятником Бухары. Его неоднократно разрушали. Но всегда заново отстраивали. Сейчас в городской крепости расположен Бухарский государственный архитектурно-художественный музей-заповедник</i>",
		"content_uz": "<p><i>Buxorodagi Ark Qal’asi sharqning Kremlidir. Qal’aning yoshi to‘g‘risida aniq ma’lumotlar yo‘q, ammo VI asrda uning devorlari mahalliy hukmdorlarni himoya qilgan.</i></p>  <p><i></i></p>  <p>XX asr boshlarida qal’ada mingga yaqin kishi yashagan. Ular asosan Amirning yaqinlari va a’yonlar edi. Yana bu yerda saroy xizmatlari, hunarmandchilik ustaxonalari va g‘aznachilik joylashgan edi. Ark Buxoro Amirligi uchun qimmatga ega barcha narsaning markazi edi.</p>    <p>Ark buyuk olimlar va arboblarni mamnuniyat bilan qabul qilgan. Butun dunyoga mashhur tabib Abu Ali ibn Sino Arkning noyob kutubxonasida qadimiy qo‘lyozmalarni o‘qir edi. Arkda yana dono ruboilari juda ko‘p tillarga tarjima qilingan Umar Hayyom yashagan.</p>  <p>Arkning paydo bo‘lishi tarixi sirlidir. Afsonaga ko‘ra Siyovush ismli yigit malikaga ko‘ngil qo‘yadi. Lekin hukmdor o‘z qizini buqa terisi ustiga saroy qura olsagina unga berishga rozi edi. Zehni o‘tkir Siyovush bu holatning yechimini topdi. U terini ingichka qilib kesib, uchlarini birlashtirdi va shartli xalqa ichida chiroyli saroyni barpo etadi.</p>    <p><strong>Tuzilishi va me’morchilik</strong></p>  <p>Muhtasham va mustahkam istehkom Registon maydonida joylashgan. Balandligi 16-20 metrni tashkil etgan qalin devorlar qariyb 800 metrga cho‘zilgan edi. Ulardan birida katta charm kamchi  savlat to‘kib turar edi. Bu Buxoro Amirining hokimiyati ramzi edi.</p>  <p>Barcha saqlanib qolgan binolar XVII-XX asrlarga tegishlidir. Qa’laga asosiy kirish yo‘li ikkita minora bilan bezatilgan. Maxsus galereya yordamida ular qorovulxona va ayvonlar bilan birlashtirilgan.Darvozaga ko‘tarilish esa pandus shaklidadir. Usti yopiq uzun yo‘lakdan u Jome masjidiga olib boradi.</p>    <p>Ark qal’asi Buxoroning eng qadimiy me’moriy va Arxeologik yodgorligi hisoblanadi. Uni ko‘p bora vayron qilishgan. Ammo har doim qayta tiklangan. Hozirda shahar qal’asida Buxoro davlat badiiy-me’morchilik muzey-qo‘riqxonasi joylashgan.</p>  <p><strong></strong></p>",
		"content_en": "<p><i>Fortress Ark in Bukhara represents itself as Eastern Kremlin. There is no precise data on its age, the walls of fortress reliably protected the local rulers in the VI century.</i></p>  <p>At the beginning of XX century, about 3,000 people lived in the citadel. Mainly they were close people to Emir and the elite. Palace service, craft shops and treasury were also located here. Ark was center point for everything, which represented special value for Emirate of Bukhara.</p>  <p>It welcomed the great scholars and figures. The world-famous doctor Avicenna read ancient manuscripts in the unique library of Ark. Poet Omar Khayyam, whose wise rubai translated into many languages, also lived here.</p>  <p>The history of creation of Ark is shrouded in mystery. According to legend, handsome young person Siyavush fell in love with a local princess. But the governor agreed to permit them to marry provided that Siyavush would first build a palace on the area bounded by a bull skin. Smart Siyavush found the way out quickly. He cut the bull skin into slender strips, connected the ends, and inside this boundary built the palace.</p>  <p><strong>Design and architecture</strong></p>  <p>The majestic and impregnable fortification was on the Registan Square. The length of the thick walls with the 16-20 m in height was almost 800 m. A large leather whip was installed in one of the wall. It was a symbol of the power of the Emir of Bukhara.</p>  <p>All the remaining buildings in Ark belong to XVII - XX centuries. The front entrance to the fortress is decorated with two towers. Using a special gallery, they are connected to the guard rooms and terraces. Ascent to the main gate looks like a ramp. It leads to Jome mosque through long roofed corridor.</p>  <p>Ark Fortress is the oldest architectural and archeological monument of Bukhara. The fortress was destroyed several times. But it was rebuilt again and again. Now Bukhara State Architecture and Art Museum-Reserve is located at the fortress.</p>",
		"audio_ru": "/uploads/audio/eaf304cd137fd95cd4f51de9b2b1957b_mp3_ru.mp3",
		"audio_uz": "/uploads/audio/eadd4ba3a351b168d8745b046b7c5cc6_mp3_uz.mp3",
		"audio_en": "/uploads/audio/e55f5e62f79fc91ee2c77ce8ac5ad8bf_mp3_en.mp3",
		"qr_href": "http://test",
		"pic_360": "/uploads/360/4819cab077d7aa7108eb5d3ad5d3cf76_360.jpg",
		"pic_simple": "http://qr360.verstka.uz/web/uploads/simple/aa6ba9257889c62a226087230b18b3e7.jpeg",
		"view": 0,
		"sort": null,
		"featured": 1
	},
	{
		"id": 24,
		"city_id": 2,
		"title_ru": "Ак-Мечеть",
		"title_uz": "Oq Masjid",
		"title_en": "Ak Mosque",
		"waymark_ru": "",
		"waymark_uz": "",
		"waymark_en": "",
		"content_ru": "<p><i>Хива – один из древнейших городов Узбекистана. Она сохранила свою самобытность и первозданную архитектуру.</i></p>  <p>Каждое здание и улочка здесь буквально дышит историей. Среди многочисленных памятников особо выделяется внутренний город Ичан-кала. Это живой город-музей под открытым небом, в котором проживают около 300 семей.</p>  <p>В нем расположены роскошные дворцы правителей, многочисленные медресе и мечети с высокими минаретами, богато украшенные мавзолеи, а также торговые площади, среди которых есть даже невольничий рынок.</p>  <p>Одним из значимых религиозных сооружений Хивы является Ак-мечеть. Слово «мечеть» имеет арабские корни - «масжид». Ак–масжид отличается весьма необычной архитектурой и находится недалеко от восточных ворот Палван-дарвоза.</p>  <p>Ее возводили в несколько этапов. В 1647 году при шейбаниде Ануш-хане заложили фундамент мечети. Однако, судя по надписи на ее дверях, строительство завершили лишь в эпоху правления династии Кунграт в 1838-42 гг. Та же надпись гласит, что резьбу по дереву выполняли местные прославленные мастера Каландар и Нур Мухаммад.</p>  <p>Мечеть построена в виде купольного зала. К нему примыкают три галереи. А снаружи с трех сторон окружают айваны (терраса) с деревянными колоннами.</p>  <p>Поскольку она служит квартальной мечетью для каждодневных молитв, то выглядит довольно скромно. В ее отделке нет каких-либо сложных узоров. Стены просто покрыты белой ганчевой штукатуркой. Однако двери и окна украшает тончайшая резьба по дереву, что несколько оживляет внешнее и внутреннее убранство. В оконные рамы вставлены ганчевые решётки с ажурным узором.</p>  <p><i>Несмотря на компактность и простоту, Ак-масжид - это одно из красивейших сооружений средневековой Хивы, которое сразу выделяется среди других мечетей Ичан-калы.</i></p>",
		"content_uz": "<p><i>Xiva O‘zbekistonning eng qadimiy shaharlaridan biridir. U o‘ziga xosligi va me’morchiligining dastlabki ko‘rinishlarini saqlab qolgan.</i></p>  <p>Shaharning har bir binosi va ko‘chasi mubolag‘asiz o‘z tarixiga egadir. Ko‘p sonli yodgorliklarning ichida “Ichan qal’a” alohida ajralib turadi. Bu 300 oila yashovchi ochiq havoda joylashgan gavjum muzey-shahardir.</p>  <p>Uning ichida hukmdorlarning hashamatli saroylari, ko‘p sonli madrasalar, baland minorali masjidlar, hashamat bilan bezatilgan maqbaralar hamda savdo maydonlari joylashgan. Savdo maydonlari orasida hatto qullar bozori ham mavjud.</p>  <p>Oq masjid Xivaning muhim diniy inshootlaridan biridir. Masjid - so‘zi arab tilidan olingan. Polvon darvozasi yaqinida joylashgan Oq masjid o‘zgacha me’morchiligi bilan ajralib turadi.</p>  <p>U bir necha bosqichda barpo etilgan. 1647-yilda Shayboniylar sulolasi vakili Anushxon davrida masjidning poydevori qurilgan. Ammo uning eshiklarida qolgan yozuvlarga ko‘ra masjidning qurilishi faqatgina 1838-1842 yillarga kelibgina o‘z yakuniga yetadi. Bu paytga kelib davlat boshqaruvi Qo‘ng‘irot sulolasi qo‘liga o‘tgan edi. Yana shu yozuvlardan bilsak bo‘ladiki yog‘och o‘ymakorligi ishlarini mashhur mahalliy usta Qalandar va usta Nur Muhammad bajarganlar.</p>  <p>Masjid gumbazli xona ko‘rinishida qurilgan. Unga uchta tor galereya tutashgan. Tashqi tomoni esa yog‘och ustunli uchta ayvon bilan o‘rab olingan.</p>  <p>Masjid har kunlik namoz o‘qilishi uchun xizmat qilgani sababli anchagina oddiy ko‘rinishga ega. Uni bezashda naqshlardan deyarli foydalanilmagan. Devorlari oq ganch suvoq bilan qoplangan. Faqatgina uning eshiklari va romlarida ishlatilgan nafis yog‘och o‘ymakorligi ichki va tashqi ko‘rinishini biroz jonlantiradi. Deraza romlariga ganch panjaralar o‘rnatilgan.</p>  <p><i>O‘rta asr Xivasining eng go‘zal inshootlaridan biri bo‘lgan Oq masjid o‘zining oddiyligi va ihchamligiga qaramay Ichan qal’aning boshqa masjidlaridan yaqqol ajralib turadi.</i></p>",
		"content_en": "<p><i>Khiva is one of ancient cities of Uzbekistan. The city preserved its originality and primeval architecture.</i></p>  <p><i>Literally, each building and street in Khiva breathes history. Inner city Ichan-kala can be highlighted among many attractions. This is live open air city-museum. About 300 families are living here. </i></p>  <p>Luxury palaces of the rulers, many madrasahs and mosques with high minarets, mausoleums with rich decorations, as well as trade squares, including slave market, are located in Ichan-kala.</p>  <p>Ak Masjid is one of the most significant religious buildings of Khiva. Masjid (mosque) has roots from Arab language. Ak Masjid has unusual architecture and is located near of Eastern Gates Palvan-darvoza.</p>  <p>It was built in several phases. The foundation of the mosque was constructed in 1647 during rule of Sheybanid Anush-khan. However, according to scripts on its doors, the construction was completed in epoch of the rule of Kungrat dynasty in 1838-42. The scripts on the door also say that local masters Kalandar and Nur Mukhammad made the wood engraving.</p>  <p>The mosque was constructed in form of dome hall. Three galleries are adjoining to it. Aivans (terraces) with wooden columns surround it from outside.</p>  <p>Ak Mosque was a block mosque for daily prayers, it was built and decorated without special ornamental excessiveness. There are no difficult ornaments in its decoration. The walls covered only with ganch plasters. However, the doors and windows were decorated with finest wood engraving, which improves external and internal decoration. The windows of Ak Masjid are decorated with ganch grids representing a polyfoil.</p><p>Ak Masjid has compact size and looks simple. However, Ak Masjid is one of the most beautiful medieval buildings of Khiva. The mosque stands out among the other mosques of Ichan-kala.</p>",
		"audio_ru": "/uploads/audio/21eed9505524cce1c5e0582b19e06967_mp3_ru.mp3",
		"audio_uz": "/uploads/audio/cb8b16330e3502d9d6f65e1624927456_mp3_uz.mp3",
		"audio_en": "/uploads/audio/075d05bb9e3fcd3eac27f0b638c55b53_mp3_en.mp3",
		"qr_href": "http://qr360.verstka.uz/en/attraction/update?id=24",
		"pic_360": "/uploads/360/ak-mechet.jpg",
		"pic_simple": "http://qr360.verstka.uz/web/uploads/simple/28a4a86246b062d65d2035bd3d55a395.jpg",
		"view": 0,
		"sort": null,
		"featured": 0
	}, 
	{
	    "id": 25,
	    "city_id": 2,
	    "title_ru": "Архитектурный комплекс Пахлавана Махмуда",
	    "title_uz": "Pahlavon Mahmud me’moriy majmuasi",
	    "title_en": "Architectural complex of Pakhlavan Makhmud",
	    "waymark_ru": "",
	    "waymark_uz": "",
	    "waymark_en": "",
	    "content_ru": "<p><i>В фольклоре всех народов существуют эпосы о героях с отважным сердцем и богатырской силой. В Центральной Азии их величают пахлаванами. Одним из самых знаменитых является Пахлаван Махмуд из Хорезма. </i></p>  <p>Он работал простым скорняком, то есть мастером по выделке мехов. Но в душе был великим борцом, чем и прославился далеко за пределами родного города. Лишь однажды, чтобы спасти соперника от казни в случае поражения, он поддался. До сих пор перед выходом на бой иранские борцы просят великого Пахлавана Махмуда о победе.</p>  <p>С ним связана еще одна красивая легенда. Когда хорезмиец одержал победу в другой стране, правитель спросил что дать ему в награду. Пахлаван Махмуд ответил, что заберет домой столько хорезмийцев, сколько поместится в его пояс. Он разрезал кожу коровы на тонкие полоски и связал вместе. Затем опоясал всех пленных хорезмийцев и увез с собой.</p>  <p>Помимо этого, он отлично сочинял стихи и был мудрым философом.</p>  <p>По легенде, Пахлаван Махмуд умер в 1322 или в 1325 году. Героя похоронили прямо во дворе его мастерской. Жители Хивы стали почитать Пахлавана Махмуда своим покровителем и в 1701 г. построили над его могилой усыпальницу. Надгробие и само сооружение украсили традиционной бело-голубой майоликой, что характерно для ханских мавзолеев. </p>  <p>Сюда стали стекаться многочисленные паломники. И в первой половине XIX века к нему пристроили восточную галерею. В мавзолее также стали хоронить правителей, тем самым превратив в усыпальницу хивинских ханов.</p>  <p>В конце XIX века к нему достроили мечеть, медресе и четыре благотворительных заведения (карихона), в которых жили слепцы. Из-за песчаных бурь хорезмцы часто страдали этим недугом.</p>  <p>Для паломников построили жилые комнаты – худжры и столовую с кухней - ошхону. В начале XX века перед мавзолеем возвели двухэтажное здание, где находится красиво декорированная усыпальница Исфандияр-хана.</p>  <p><i>Рядом с архитектурным ансамблем Пахлавана Махмуда находится старая квартальная мечеть для каждодневных молитв Ак-мечеть.</i></p>",
	    "content_uz": "<p><i>Har bir millatning xalq og‘zaki ijodida jasur va kuchli qahramonlar haqida dostonlar mavjud. Markaziy Osiyoda shunday qahramonlarni pahlavonlar deb atashadi. Eng mashhur pahlavonlardan biri bu xorazmlik Pahlavon Mahmuddir.</i></p>  <p>U oddiy mo‘ynado‘z bo‘lishiga qaramay uzoq uzoqlarga buyuk kurashchi sifatida dong‘i ketadi. U faqatgina birbora yutqazgan. Pahlavon Mahmud o‘zining raqibi unga yutqazsa qatl etilishini bilib, unga atayin yutqazib bergan. Hozirgi kunda ham eronlik kurashchilar olishuvga chiqishdan oldin Pahlavon Mahmudning ruhidan g‘alabani so‘rashadi.</p>  <p>Yana bir chiroyli afsonaga ko‘ra u boshqa mamlakatda g‘alabaga erishadi. Shu mamlakat hukmdori unga mukofot sifatida nima istashini so‘raydi. Shunda Pahlavon Mahmud belbog‘iga sig‘ganicha xorazmliklarni uyiga olib ketmoqchiligini aytadi. U sigir terisini ingichka tasma qilib kesib hamma asir xorazmliklarni beliga belbog‘ qilib bog‘laydi va o‘zi bilan olib ketadi.</p>  <p>Undan tashqari u yaxshi she’rlar yozgan va dono faylasuf bo‘lgan.</p>  <p>Afsonaga ko‘ra Pahlavon Mahmud 1322 yoki 1325-yili vafot etgan. Uni o‘zining ustaxonasining hovlisida dafn etganlar. Xivaliklar uni o‘zlarining homiylari sifatida izzatlashar edi. 1701-yilda esa uning qabri ustiga sag‘ana barpo etdilar. Inshootning o‘zi va qabr toshini xon maqbalariga xos an’anaviy oq va moviy koshinlar bilan bezatishgan.</p>  <p>Bu yerga ko‘p sonli ziyoratchilar kela boshladi. XIX asrning birinchi yarmida inshootga taqab sharqiy galereya ham barpo etildi. Maqbarada hukmdorlarni ham dafn eta boshlashdi, shu sababli uni Xiva xonlari sag‘anasiga aylantirdilar.</p>  <p>XIX asrning oxirida maqbarada masjid, madrasa va ko‘r insonlar yashaydigan to‘rt xayriya muassasalarini (qorixona) barpo etadilar. Qum bo‘ronlari tufayli xorazmliklar bu dardga tez-tez chalinar edi.</p>  <p>Ziyoratchilar uchun yotoqxonalar – hujralar va oshxona qurdilar. XX asrning boshida maqbara oldida ikki qavatli bino barpo etildi. Binoda Isfandiyorxonning chiroyli bezatilgan sag‘anasi joylashgan.</p>  <p><i>Pahlavon Mahmud me’moriy ansambli yaqinida namoz o‘qish uchun Oq Masjid joylashgan.</i></p>",
	    "content_en": "<p><i>There are epics about heroes with the brave heart and strong power in folklore of all nations. People of Central Asia call such people as pakhlavans. One of such famous people is Pakhlavan Makhmud from Khorezm. </i></p>  <p>He worked as furrier or master on fur processing. He was great wrestler in his soul. That’s why he became famous far beyond his native city. He lost only once to save his opponent from death penalty. Still Iranian wrestlers ask for victory from Pakhlavan Makhmud before the bouts.</p>  <p>There is also one beautiful legend related to him. When Pakhlavan Makhmud won in foreign state, the ruler asked what to gift him as a prize. Pakhlavan Makhmud said he will take home all those, who would fit into a cow skin. He cut the skin into thin strips, tied them into one large belt and wrapped all the prisoners from Khorezm with the belt and took them home with himself. Besides, he was excellent poet and wise philosopher.</p>  <p>According to legend, Pakhlavan Makhmud died in 1322 or in 1325. He was buried in the yard of his shop. </p>  <p>Khiva residents esteem Pakhlavan Makhmud as their protector and they construct the mausoleum over his tomb in 1701. Tombstone and the building were decorated with traditional blue and white majolica, which is typical for Khan’s mausoleums.</p>  <p>Large number of pilgrims began to come here. Eastern gallery was constructed here in the first half of the 19<sup>th</sup> century. The mausoleum also became burial place for Khiva khans as the rulers were buried here.</p>  <p>In the end of the 19 century, the mosque, madrasah and four charity establishments (karihona), where the blind people lived, were built here. People of Khorezm suffered from blindness due frequent sandy storms.</p>  <p>Hudjra (living rooms) and oshhona (kitchen) were also constructed for pilgrims. Two-storey building was built in front of the mausoleum, where beautifully decorated burial-vault of Isfandiyar-khan is located.</p>  <p>Old block mosque for daily prayers Ak Masjid is located near architectural ensemble Pakhlavan Makhmud.</p>",
	    "audio_ru": "/uploads/audio/e032d344815c443001b35a1c921d8742_mp3_ru.mp3",
	    "audio_uz": "/uploads/audio/6f811c87f862ce08bf7c78b52aba83c0_mp3_uz.mp3",
	    "audio_en": "/uploads/audio/abc8d65a88279a5558d6308fc02f5630_mp3_en.mp3",
	    "qr_href": "",
	    "pic_360": "/uploads/360/pahlavan-mahmud.jpg",
	    "pic_simple": "http://qr360.verstka.uz/web/uploads/simple/2985468c7b0ce461e15e933f08ada2f7.jpeg",
	    "view": 0,
	    "sort": null,
	    "featured": 1
  	},
    ];
	
	this.setState({
		items: data
	});
}

render() {
	
	return (
		<div>
			{this.state.items.map((attr, i) => <Attr title={attr.title_ru} imgLink={attr.pic_simple} key={i} id={attr.id} />)}			
		</div>
		);
	}
}